HalicHub/Models/Article/ArticleDetailsModel.cs
using Halic.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HalicHub.Models
{
    public class ArticleDetailsModel
    {
        public Article Articles { get; set; }
        public List<Author> Authors { get; set; }
        public List<Category> Categories { get; set; }
        public List<Article> Articlescategory { get; set; }

    }
}
    

HalicHub/Models/Article/ArticleListViewModel.cs
using Halic.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HalicHub.Models
{
    public class ArticleListViewModel
    {
        public PageInfo pageInfo { get; set; }

        public List<Article> Articles { get; set; }
    
    }
}

HalicHub/Models/Author/AuthorDetailModel.cs
using Halic.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HalicHub.Models
{
    public class AuthorDetailModel
    {
        public Author Authors { get; set; }
        public List<Article> Articles { get; set; }
        public List<Category> Categories { get; set; }
        public List<News> News { get; set; }


    }
}

HalicHub/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Halic.Bussiness.Abstract;
using Halic.Entity;
using HalicHub.Extensions;
using HalicHub.Identity;
using HalicHub.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace HalicHub.Controllers
{
    [Authorize]
    //BURAYA MUTLAKA YETKİLENDİRİLMİŞ GİRER DEMEK
    public class AdminController : Controller
    {
        private IArticleServices _articleServices;
        private ICategoryServices _categoryServices;
        private IAuthorServices _authorServices;
        private INewsServices _newsServices;
        private INCategoryServices _nCategoryServices;
        private IVideoServices _videoServices;
        private ISliderServices _sliderServices;
        private IActivitiesServices _activitiesServices;
        private IEMailServices _emailServices;

        private readonly IHostingEnvironment _env;

        //Rol İşlemleri

        //private RoleManager<IdentityRole> _roleManager;
        //private UserManager<User> _UserManager;

        public AdminController(IArticleServices articleServices, IEMailServices eMailServices, IHostingEnvironment env, ICategoryServices categoryServices, IAuthorServices authorServices, INewsServices newsServices, INCategoryServices nCategoryServices, IVideoServices videoServices, ISliderServices sliderServices, IActivitiesServices activitiesServices)
        {
            _articleServices = articleServices;
            _categoryServices = categoryServices;
            _authorServices = authorServices;
            _newsServices = newsServices;
            _nCategoryServices = nCategoryServices;
            _videoServices = videoServices;
            _sliderServices = sliderServices;
            _activitiesServices = activitiesServices;
            //_roleManager = IdentityRole;
            //_UserManager = userManager;
            _env = env;
            _emailServices = eMailServices;
        }
        [HttpPost]
        public IActionResult UploadImage(IFormFile upload)
        {
            if (upload.Length <= 0) return null;

            var fileName = Guid.NewGuid() + Path.GetExtension(upload.FileName).ToLower();


            var path = Path.Combine(
                _env.WebRootPath, "upload/image",
                fileName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                upload.CopyTo(stream);

            }

            var url = $"{"/upload/image/"}{fileName}";

            return Json(new { uploaded = true, url });
        }
        [Authorize(Roles = "user")]
        [HttpGet]
        public IActionResult ArticleListAdmin()
        {   
            return View(new ArticleListViewModel {
              Articles=_articleServices.GetOrderAll()
            });
        }
        [Authorize(Roles = "user")]
        [HttpGet]
        public IActionResult ArticleCreateAdmin()
        {
            ViewBag.Categories = _categoryServices.GetAll();
            ViewBag.Authors = _authorServices.GetAll();
            return View();
        }
        [Authorize(Roles = "user")]
        [HttpPost]
        public async Task<IActionResult> ArticleCreateAdmin(ArticleModel model, IFormFile file,IFormCollection form)
        {
            int[] diziCategories;
            int[] diziAuthors;

            var dataCategories = Convert.ToInt32(form["categories"]);
            diziCategories = new int[] { dataCategories };

            var dataAuthors = Convert.ToInt32(form["authors"]);
            diziAuthors = new int[] { dataAuthors };

            var entity = new Article()
                {
                    Title = model.Title,
                    Content = model.Content,
                    Description = model.Description,
                    Date = model.Date,
                    Image = model.Image,
                    Url = model.Url,
                    IsApproved = model.IsApproved,
                };

                if (file != null)
                {
                    var extention = Path.GetExtension(file.FileName);
                    var randomName = string.Format($"{Guid.NewGuid()}{extention}");
                    entity.Image = randomName;
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", randomName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
                _articleServices.ArticleCreate(entity, diziCategories, diziAuthors);

                TempData.Put("message", new AlertMessage()
                {
                    Title = "Yeni Makale",
                    Message = $"{model.Title} Makale Başarıyla Eklendi",
                    AlertType = "success"
                });

                return RedirectToAction("ArticleListAdmin");
        }
        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult ArticleEditAdmin(int? id)     
        {   
            var entity = _articleServices.GetByWithCategoriesId((int)id);

            var model = new ArticleModel()
            {
                ArticleId=entity.ArticleId,
                Title = entity.Title,
                Content = entity.Content,
                Description = entity.Description,
                Date = entity.Date,
                Image = entity.Image,
                Url = entity.Url,
                IsApproved = entity.IsApproved,
                Categories=entity.ArticleCategories.Select(i=>i.Categories).ToList(),
                Authors = entity.ArticleAuthors.Select(i=>i.Authors).ToList(),
                AuthorId=entity.ArticleAuthors.Select(i=>i.AuthorId).FirstOrDefault(),
                CategoryId=entity.ArticleCategories.Select(i=>i.CategoryId).FirstOrDefault()
            };
            ViewBag.Categories = _categoryServices.GetAll();
            ViewBag.Authors = _authorServices.GetAll();

            return View(model);
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> ArticleEditAdmin(ArticleModel model,IFormFile file, IFormCollection form)
        {
            int[] diziCategories;
            int[] diziAuthors;

            var dataCategories = Convert.ToInt32(form["categories"]);
            diziCategories = new int[] { dataCategories };

            var dataAuthors = Convert.ToInt32(form["authors"]);
            diziAuthors = new int[] { dataAuthors };

            
                var entity = _articleServices.GetById(model.ArticleId);

            entity.Title = model.Title;
            entity.Content = model.Content;
            entity.Description = model.Description;
            entity.Date = model.Date;
            entity.Url = model.Url;
            entity.IsApproved = model.IsApproved;

            if (file != null)
            {
                var extention = Path.GetExtension(file.FileName);
                var randomName = string.Format($"{Guid.NewGuid()}{extention}");
                entity.Image = randomName;
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", randomName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
            }

            _articleServices.Update(entity,diziCategories,diziAuthors);

            TempData.Put("message", new AlertMessage()
            {
                Title = "Makale Güncellendi",
                Message = $"{model.Title} Makale Başarıyla Güncellendi",
                AlertType = "warning"
            });
            return RedirectToAction("ArticleListAdmin");
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public IActionResult ArticleDeleteAdmin(int ArticleId)
        {
            var entity = _articleServices.GetById(ArticleId);
            var tittle = entity.Title;
            _articleServices.Delete(entity);

            TempData.Put("message", new AlertMessage()
            {
                Title = "Makale Silindi",
                Message = $"{tittle} Makale Başarıyla Silindi",
                AlertType = "danger"
            });
            return RedirectToAction("ArticleListAdmin");
        }
        //-----------------------------------------------------------
        //MakaleKategori sayfası
        [Authorize(Roles = "admin")]
        public IActionResult ArticleCategoryListAdmin()
        {
            return View(new CategoryListViewModel
            {
                Categories = _categoryServices.GetAll()
            });
        }
        [Authorize(Roles = "admin")]
        [HttpGet]
        public IActionResult ArticleCategoryCreateAdmin()
        {
            return View();
        }
        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> ArticleCategoryCreateAdmin(CategoryModel model, IFormFile file)
        {
            var entity = new Category()
            {
                Tittle = model.Tittle,
                Url = model.Url,
            };
            if (file != null)
            {
                var extention = Path.GetExtension(file.FileName);
                var randomName = string.Format($"{Guid.NewGuid()}{extention}");
                entity.Image = randomName;
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", randomName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
            }
            _categoryServices.Create(entity);

HalicHub/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HalicHub.Identity;
using HalicHub.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HalicHub.Controllers
{
    [Authorize(Roles = "server")]

    public class RoleController : Controller
    { //Rol İşlemleri

        private RoleManager<IdentityRole> _roleManager;
        private UserManager<User> _UserManager;
        public RoleController(RoleManager<IdentityRole> IdentityRole, UserManager<User> userManager)
        {
            _roleManager = IdentityRole;
            _UserManager = userManager;
        }

        // ---------------------> Rol OPERASYONLARI <-----------------------------
        public IActionResult RoleList()
        {
            return View(_roleManager.Roles);
        }
        [HttpGet]
        public IActionResult RoleCreate()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RoleCreate(RoleModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await _roleManager.CreateAsync(new IdentityRole(model.Name));
                if (result.Succeeded)
                {
                    return RedirectToAction("RoleList");
                }
            }

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> RoleEdit(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            var members = new List<User>();
            var nonmembers = new List<User>();
            var userList = _UserManager.Users.ToList();
            foreach (var item in userList)
            {
                var list = await _UserManager.IsInRoleAsync(item, role.Name) ? members : nonmembers;
                list.Add(item);
            }
            var model = new RoleDetailModel()
            {
                Members = members,
                Role = role,
                NonMembers = nonmembers
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> RoleEdit(RoleEditModel model)
        {
            if (ModelState.IsValid)
            {
                foreach (var UserId in model.IdsToAdd ?? new string[] { })//ilgili olan role eklenen userler idleridolaşalım
                {
                    var user = await _UserManager.FindByIdAsync(UserId);//iligli userid ile useri alalım
                    if (user != null)
                    {
                        var result = await _UserManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError("", error.Description);
                            }
                        }
                    }
                }
                foreach (var item in model.IdsToDelete ?? new string[] { })
                {
                    var user = await _UserManager.FindByIdAsync(item);
                    if (user != null)
                    {
                        var result = await _UserManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError("", error.Description);
                            }
                        }
                    }
                }
            }
            return Redirect("/Role/rolelist/" + model.RoleId);
        }

        public async Task<IActionResult> RoleDelete(string RoleId)
        {
            var role = await _roleManager.FindByIdAsync(RoleId);
            await _roleManager.DeleteAsync(role);
            return RedirectToAction("RoleList");
        }

        // ------------------> User Operasyonları <-------------------------------

        public IActionResult UserList()
        {
            return View(_UserManager.Users);
        }
        [HttpGet]
        public async Task<IActionResult> UserEdit(string id)
        {
            var user = await _UserManager.FindByIdAsync(id);
            if (user != null)
            {
                var selectedRoles = await _UserManager.GetRolesAsync(user);//rol bilg aldım
                var roles = _roleManager.Roles.Select(i => i.Name);//birden fazla name seçerse diye

                ViewBag.Roles = roles;
                return View(new UserDetailModel
                {
                    UserId = user.Id,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    UserName = user.UserName,
                    Email = user.Email,
                    SelectedRoles = selectedRoles
                });
            }
            return Redirect("~/Role/userlist");
        }
        [HttpPost]
        public async Task<IActionResult> UserEdit(UserDetailModel model, string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = await _UserManager.FindByIdAsync(model.UserId);
                if (user != null)
                {
                    user.FirstName = model.FirstName;
                    user.LastName = model.LastName;
                    user.Email = model.Email;
                    user.UserName = model.UserName;

                    var result = await _UserManager.UpdateAsync(user);
                    var userRoles = await _UserManager.GetRolesAsync(user);//kullanıcı rollerini alalım
                    selectedRoles = selectedRoles ?? new string[] { };
                    await _UserManager.AddToRolesAsync(user, selectedRoles.Except(userRoles).ToArray<string>());
                    await _UserManager.RemoveFromRolesAsync(user, userRoles.Except(selectedRoles).ToArray<string>());

                    return Redirect("/Role/userlist");

                }
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> UserDelete(string RoleId)
        {
            var user = await _UserManager.FindByIdAsync(RoleId);
            await _UserManager.DeleteAsync(user);
            return RedirectToAction("UserList");
        }

        public IActionResult RoleView()
        {

            return View();
        }



    }
}

HalicHub/Views/Shared/ArticleList.cshtml
@model ArticleListViewModel
@await Html.PartialAsync("_Header")
<partial name="_Search">
    <div class="listing-area pt-120 pb-120">
        <div class="container">
            <div class="row">
                <div class="col-xl-12 col-lg-8 col-md-6">
                    <div class="popular-directorya-area fix">
                        <div class="row">
                            @foreach (var item in Model.Articles)
                            {
                <div class="col-lg-4">
                    @await Html.PartialAsync("_Article", item)
                </div>}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @await Html.PartialAsync("_Footer")

HalicHub/Views/Shared/_Activities.cshtml
@model Activities

<div class="single_study text-center">
    <div class="thumb" style="display: block">
        <a style="display: block">
            <img src="~/img/@Model.Image" alt="">

        </a>
    </div>
    <div class="subheading">
        <h4>@Model.Tittle</h4>
        <p style="padding-left: 20px; padding-right: 20px">@Model.Description</p>
    </div>
    @*<a asp-controller="home" asp-action="ActivitiesDetails" asp-route-detail="@Model.Url"><h4 style="color:black">İçerik</h4></a>*@

</div>
           

HalicHub/Views/Shared/_AdminFooter.cshtml
<footer>
    <div class="footer-area">
        <p>© Copyright 2020. Tüm hakları saklıdır. | <a href="http://www.halic.edu.tr/tr" target="_blank"> Haliç Üniversitesi</a>.</p>
    </div>
</footer>

HalicHub/Views/Shared/_AdminMenu.cshtml
<div class="sidebar-menu">
    <div class="sidebar-header">
        <!--<div class="logo">-->
        <div>
            <a href="anasayfa.html"><h1 style="color: white">Haliç HUB</h1></a>
        </div>
    </div>
    <div class="main-menu">
        <div class="menu-inner">
            <nav>
                <ul class="metismenu" id="menu">
                    <li>
                        <a href="javascript:void(0)" aria-expanded="true"><i class="ti-dashboard"></i><span>Dashboard</span></a>
                        <ul class="collapse">
                            <li><a href="anasayfa.html">Sol Menü</a></li>
                            <li><a href="anasayfa-2.html">Yatay Menü</a></li>
                        </ul>
                    </li>
                    
                    <li><a asp-controller="admin" asp-action="ArticleListAdmin"><i class="ti-book"></i> <span>Makaleler</span></a></li>
                    <li><a asp-controller="admin" asp-action="NewsListAdmin"><i class="ti-receipt"></i> <span>Haberler</span></a></li>
                   @if (User.IsInRole("admin") || User.IsInRole("server"))
                   {
                    <li><a asp-controller="admin" asp-action="ActivitiesListAdmin"><i class="ti-world"></i> <span>Etkinlikler</span></a></li>
                    <li><a asp-controller="admin" asp-action="VideoListAdmin"><i class="ti-video-clapper"></i> <span>Videolar</span></a></li>
                    <li><a asp-controller="admin" asp-action="SliderListAdmin"><i class="ti-layers-alt"></i> <span>Slider</span></a></li>
                    <li><a asp-controller="admin" asp-action="AuthorListAdmin"><i class="ti-slice"></i> <span>Yazarlar</span></a></li>
                    <li><a asp-controller="admin" asp-action="EMailList"><i class="ti-slice"></i> <span>EMail</span></a></li>
                   }
                    @if (User.IsInRole("server"))
                    {
                         <li><a asp-controller="Role" asp-action="RoleList"><i class="ti-slice"></i> <span>Roller</span></a></li>
                         <li><a asp-controller="Role" asp-action="UserList"><i class="ti-slice"></i> <span>Kullanıcılar</span></a></li>
                    }
                         <li><a asp-controller="Account" asp-action="Logout"><i class="ti-slice"></i> <span>Çıkış Yap</span></a></li>

                     @if (User.IsInRole("admin") || User.IsInRole("server"))
                     {
                    <li>
                        <a href="javascript:void(0)" aria-expanded="true"><i class="ti-dashboard"></i><span>Kategoriler</span></a>
                        <ul class="collapse">
                            <li><a asp-controller="admin" asp-action="ArticleCategoryListAdmin">Makale Kategorileri</a></li>
                            <li><a asp-controller="admin" asp-action="NewsCategoryListAdmin">Haber Kategorileri</a></li>
                        </ul>
                    </li>
                     }
                </ul>
            </nav>
        </div>
    </div>
</div>

HalicHub/Views/Shared/_Article.cshtml
@model Article

<div class="properties pb-20">
    <div class="properties__card">
        <div class="properties__img overlay1">
            <a asp-controller="home" asp-action="ArticleDetails" asp-route-url="@Model.Url"><img src="~/img/@Model.Image" alt=""></a>
            @*<div class="icon">
                            @foreach (var item in Model.ArticleCategories)
                            {
                <h3 style="font-size: 1em; padding: 5px; background: #07233d; color: white; border-radius: 8px">@item.Categories.Name</h3>}
                        </div>*@
        </div>
        <div class="properties__caption">
            <h3 style="font-weight: 700"><a asp-controller="home" asp-action="ArticleDetails" asp-route-url="@Model.Url">@Model.Title</a></h3>
            <p> @Model.Description</p>
        </div>
    </div>
</div>

HalicHub/Views/Shared/_AuthorSearch.cshtml
<section class="hero set-bg" data-setbg="/img/makale.jpg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="hero__text">
                    <div class="hero__search__form">
                        <form action="/AuthorSearch">
                            <input style="float: none" name="q" type="text" placeholder="Search...">
                            <button type="submit">Sorgula</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

HalicHub/Views/Shared/_Categories.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<Category>
<div class="list-group">
    <a href="/products" class="list-group-item list-group-item-action">Tüm Kategoriler</a>
    <a href="/products" class="list-group-item list-group-item-action">Bilim</a>
    <a href="/products" class="list-group-item list-group-item-action">Yazılım</a>

HalicHub/Views/Shared/_Footer.cshtml
<footer style="background-color: #001d38; padding: 100px">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="footer__address">
                    <ul>
                        <li>
                            <i class="fa fa-phone"></i>
                            <p>Telefon</p>
                            <h6>(0212) 924 2444</h6>
                        </li>
                        <li>
                            <i class="fa fa-envelope"></i>
                            <p>Email</p>
                            <h6>info@halic.edu.tr</h6>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 offset-lg-1 col-md-6">
                <div class="footer__social">
                    <h2>BİZİ TAKİP EDİN!</h2>
                    <div class="footer__social__links">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-6">
                <div class="footer__newslatter">
                    <h4>E-BÜLTEN</h4>
                    <form asp-controller="Admin" asp-action="Email">
                        <input name="NameSurname" type="text" placeholder="Ad Soyad">
                        <input name="Email" type="text" placeholder="Email">

                        <button type="submit"><i class="fa fa-send-o"></i></button>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer__copyright__text">
            <p style="color: white">
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> 2020 Tüm hakları saklıdır. İzin almadan kullanılamaz. | Haliç Üniversitesi
            </p>
        </div>
    </div>
</footer>

HalicHub/Views/Shared/_IndexArticle.cshtml
@model ArticleListViewModel


@foreach (var item in Model.Articles)
{
<div class="col-lg-12 speaker-wrap ftco-animate d-flex lg-mobil">
    <div class="row">
        <div style="text-align: center" class="col-lg-4 article-width">
            <img src="~/img/@item.Image">
        </div>
        <div style="margin: auto" class="col-lg-8 article-width">
            <h2><a class="font-sz" style="font-weight: 700" href="#">@item.Title</a></h2>
            <p class="font-p-sz">@item.Description</p>
            <h3 style="font-weight: 700" class="speaker-name font-sz">&mdash; <a href="#">@item.ArticleAuthors</a></h3>
        </div>
    </div>
</div>}

HalicHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Haliç Teknoloji Portalı</title>
    <link rel="icon" type="image/jpg" href="/img/favicon.png" sizes="32x32">
    <link href="~/css/nice-select.css" rel="stylesheet" />
    <link href="~/css/animate.css" rel="stylesheet" />
    <link href="~/css/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/css/themify-icons.css" rel="stylesheet" />
    <link href="~/css/slick.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/fonts/ionicons.css" rel="stylesheet" />
    <script type="text/javascript" src="https://platform-api.sharethis.com/js/sharethis.js#property=5f84041652383d0019108535&product=inline-share-buttons" async="async"></script>
</head>
<body style=" background-color: #f2f2f3">

    @RenderBody()

    <script src="~/js/jquery-2.2.4.min.js"></script>
    <script src="~/js/plugins.js"></script>
    <script src="~/js/active.js"></script>
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/scrollax.min.js"></script>
    <script src="~/js/main-1.js"></script>
    <script src="~/js/jquery.slicknav.min.js"></script>
    <script src="~/js/owl.carousel.min-2.js"></script>
    <script src="~/js/slick.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/main-2.js"></script>
    <script src="~/js/main-3.js"></script>
    <script src="~/js/stellar.js"></script>
    <script src="~/js/theme.js"></script>
    <script src="~/js/main-4.js"></script>
    <script src="~/js/main-5.js"></script>
    <script src="~/js/scripts.js"></script>
</body>
</html>

HalicHub/Views/Shared/_ResultMessage.cshtml
@model AlertMessage

<div class="row">
    <div class="col-md-12">
        <div class="col-md-12">
            <div class="alert alert-@Model.AlertType">
                <h4 class="alert-tittle">@Model.Title</h4>
                <p>@Model.Message</p>
            </div>
        </div>
    </div>

HalicHub/Views/Shared/_Slider.cshtml
@model Slider

<div class="item">
    <div class="post_s_item">
        <div class="post_img">
            <img src="~/img/@Model.Image" alt="">
        </div>
        <div class="post_text">
            <a href="@Model.Url"><h4>@Model.Tittle</h4></a>
            <p style="margin: 0px">@Html.Raw(Model.Description)</p>
        </div>
    </div>
</div>

HalicHub/Views/Shared/_Video.cshtml
@model Video

<div class="col-lg-6 col-md-6 col-sm-6 mix branding">
    <div class="portfolio__item">
        <div style="border-radius: 15px" class="portfolio__item__video set-bg video-sz" data-setbg="/img/@Model.Image">
            <button type="button" class="video-btn play-btn" data-toggle="modal" data-src="https://www.youtube.com/embed/@Model.Url" data-target="#myModal">
                <i class="fa fa-play"></i>
            </button>
        </div>
        <div class="portfolio__item__text">
            <h4>@Model.Tittle</h4>
            <span>@Model.Date</span>
        </div>
    </div>
</div>